default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_39645_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_39645_test

production:
  <<: *default
  adapter: postgresql
  password: <%= ENV["PROTOSPACE_39645_DATABASE_PASSWORD"] %>

